name: 🇸🇷 Build Potomitan Kreyol Keyboard - Detailed Steps

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - '.github/workflows/**'
      - 'Dictionnaries/**'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - 'Dictionnaries/**'
  workflow_dispatch:

jobs:
  # 📊 ÉTAPE 1 : GÉNÉRATION DICTIONNAIRE
  generate-dictionary:
    name: 🔤 Generate Kreyòl Dictionary
    runs-on: ubuntu-latest
    
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      
    outputs:
      dict-count: ${{ steps.stats.outputs.dict-count }}
      ngrams-count: ${{ steps.stats.outputs.ngrams-count }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Generate Fresh Kreyòl Dictionary
      run: |
        echo "🔄 Generating fresh Kreyòl dictionary from Hugging Face..."
        echo "🔑 Token configuré: $(if [ -n "$HF_TOKEN" ]; then echo "✅ Oui"; else echo "❌ Non"; fi)"
        
        cd Dictionnaires
        python -m pip install --upgrade pip
        pip install datasets huggingface_hub
        python KreyolComplet.py

    - name: 📊 Copy Assets to Flutter Project
      run: |
        echo "📂 Copying generated assets..."
        mkdir -p clavier_creole/assets/
        cp Dictionnaires/creole_dict.json clavier_creole/assets/
        cp Dictionnaires/creole_ngrams.json clavier_creole/assets/

    - name: 📈 Dictionary Statistics
      id: stats
      run: |
        DICT_COUNT=$(jq 'length' clavier_creole/assets/creole_dict.json)
        NGRAMS_COUNT=$(jq 'length' clavier_creole/assets/creole_ngrams.json)
        echo "📊 Dictionary: $DICT_COUNT words, $NGRAMS_COUNT N-grams"
        echo "dict-count=$DICT_COUNT" >> $GITHUB_OUTPUT
        echo "ngrams-count=$NGRAMS_COUNT" >> $GITHUB_OUTPUT

    - name: 📤 Upload Dictionary Assets
      uses: actions/upload-artifact@v4
      with:
        name: kreyol-dictionary-assets
        path: |
          clavier_creole/assets/creole_dict.json
          clavier_creole/assets/creole_ngrams.json
        retention-days: 1

  # 🔧 ÉTAPE 2A : BUILD DEBUG APK
  build-debug-apk:
    name: 🔧 Build Debug APK
    runs-on: ubuntu-latest
    needs: generate-dictionary
    
    env:
      KEYSTORE_FILE: potomitan-keystore.jks
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7
        cache-read-only: false

    - name: 📥 Download Dictionary Assets
      uses: actions/download-artifact@v4
      with:
        name: kreyol-dictionary-assets
        path: ./dictionary-temp

    - name: 📋 Copy Dictionary to Android Assets
      run: |
        mkdir -p android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_dict.json android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_ngrams.json android_keyboard/app/src/main/assets/

    - name: 🧹 Clean Project
      run: cd android_keyboard && gradle clean --no-daemon --scan

    - name: 🔨 Build Debug APK
      run: cd android_keyboard && gradle assembleDebug --no-daemon --scan

    - name: 📤 Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: kreyol-keyboard-debug-apk
        path: android_keyboard/app/build/outputs/apk/debug/*.apk
        retention-days: 7

  # 📦 ÉTAPE 2B : BUILD DEBUG AAB  
  build-debug-aab:
    name: 📦 Build Debug AAB
    runs-on: ubuntu-latest
    needs: generate-dictionary
    
    env:
      KEYSTORE_FILE: potomitan-keystore.jks
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7
        cache-read-only: false

    - name: 📥 Download Dictionary Assets
      uses: actions/download-artifact@v4
      with:
        name: kreyol-dictionary-assets
        path: ./dictionary-temp

    - name: 📋 Copy Dictionary to Android Assets
      run: |
        mkdir -p android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_dict.json android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_ngrams.json android_keyboard/app/src/main/assets/

    - name: 📦 Build Debug AAB
      run: cd android_keyboard && gradle bundleDebug --no-daemon --scan

    - name: 📤 Upload Debug AAB
      uses: actions/upload-artifact@v4
      with:
        name: kreyol-keyboard-debug-aab
        path: android_keyboard/app/build/outputs/bundle/debug/*.aab
        retention-days: 7

  # 🚀 ÉTAPE 3A : BUILD RELEASE APK
  build-release-apk:
    name: 🚀 Build Release APK
    runs-on: ubuntu-latest
    needs: generate-dictionary
    
    env:
      KEYSTORE_FILE: potomitan-keystore.jks
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7
        cache-read-only: false

    - name: 📥 Download Dictionary Assets
      uses: actions/download-artifact@v4
      with:
        name: kreyol-dictionary-assets
        path: ./dictionary-temp

    - name: 📋 Copy Dictionary to Android Assets
      run: |
        mkdir -p android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_dict.json android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_ngrams.json android_keyboard/app/src/main/assets/

    - name: 🔐 Generate Debug Keystore (CI Only)
      run: |
        cd android_keyboard
        echo "🔑 Generating debug keystore for CI build..."
        keytool -genkey -v -keystore app/debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

    - name: 🧹 Clean Project  
      run: cd android_keyboard && gradle clean --no-daemon --scan

    - name: 🚀 Build Release APK
      run: cd android_keyboard && gradle assembleRelease --no-daemon --scan

    - name: 📤 Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: kreyol-keyboard-release-apk
        path: android_keyboard/app/build/outputs/apk/release/*.apk
        retention-days: 30

  # 🎯 ÉTAPE 3B : BUILD RELEASE AAB
  build-release-aab:
    name: 🎯 Build Release AAB  
    runs-on: ubuntu-latest
    needs: generate-dictionary
    
    env:
      KEYSTORE_FILE: potomitan-keystore.jks
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7
        cache-read-only: false

    - name: 📥 Download Dictionary Assets
      uses: actions/download-artifact@v4
      with:
        name: kreyol-dictionary-assets
        path: ./dictionary-temp

    - name: 📋 Copy Dictionary to Android Assets
      run: |
        mkdir -p android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_dict.json android_keyboard/app/src/main/assets/
        cp dictionary-temp/creole_ngrams.json android_keyboard/app/src/main/assets/

    - name: 🔐 Generate Debug Keystore (CI Only)
      run: |
        cd android_keyboard
        echo "🔑 Generating debug keystore for CI build..."
        keytool -genkey -v -keystore app/debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

    - name: 🎯 Build Release AAB
      run: cd android_keyboard && gradle bundleRelease --no-daemon --scan

    - name: 📤 Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: kreyol-keyboard-release-aab  
        path: android_keyboard/app/build/outputs/bundle/release/*.aab
        retention-days: 30

  # 📱 ÉTAPE 4 : VALIDATION & TESTS
  validate-builds:
    name: 🔍 Validate Builds
    runs-on: ubuntu-latest
    needs: [build-debug-apk, build-debug-aab, build-release-apk, build-release-aab]
    
    steps:
    - name: 📥 Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./all-builds

    - name: 📊 Build Summary
      run: |
        echo "🎯 BUILD VALIDATION SUMMARY"
        echo "=========================="
        
        find ./all-builds -name "*.apk" -o -name "*.aab" | while read file; do
          echo "📱 $(basename "$file"): $(stat -f%z "$file" 2>/dev/null || stat -c%s "$file") bytes"
        done

    - name: ✅ Mark Builds Valid
      run: echo "✅ All builds completed successfully!"

  # 🎉 ÉTAPE 5 : CRÉATION RELEASE (si tag)
  create-release:
    name: 🎉 Create Release
    runs-on: ubuntu-latest
    needs: [validate-builds]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: 📥 Download Release Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: kreyol-keyboard-release-*
        path: ./release-artifacts

    - name: 🎉 Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: 🇸🇷 Kreyòl Keyboard ${{ github.ref }}
        body: |
          🎯 **Clavier Kreyòl Potomitan Release**
          
          📱 **Android APK & AAB disponibles**
          - APK Release pour installation directe
          - AAB Bundle pour Google Play Store
          
          🔤 **Dictionnaire enrichi**
          - Mots créoles actualisés via Hugging Face
          - N-grammes optimisés pour prédiction
          
          📊 **Build Scans disponibles** pour diagnostic complet
          
          Compatible Samsung A21s et autres appareils Android 🚀
        draft: false
        prerelease: false

    - name: 📎 Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-artifacts/kreyol-keyboard-release-apk/app-release.apk
        asset_name: KreyolKeyboard-${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive

    - name: 📎 Upload Release AAB
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-artifacts/kreyol-keyboard-release-aab/app-release.aab
        asset_name: KreyolKeyboard-${{ github.ref_name }}.aab
        asset_content_type: application/octet-stream