name:  Build Potomitan Kreyol Keyboard APK

on:
  push:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - '.github/workflows/**'
      - 'Dictionnaries/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - 'Dictionnaries/**'
  workflow_dispatch:

jobs:
  validate-dictionaries:
    name:  Validate Créole Dictionaries
    runs-on: ubuntu-latest
    
    steps:
    - name:  Checkout Repository
      uses: actions/checkout@v4
      
    - name:  Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

  build:
    name:  Build Samsung-Compatible APK
    runs-on: ubuntu-latest
    needs: validate-dictionaries
    
    steps:
    - name:  Checkout Repository
      uses: actions/checkout@v4
      
    - name:  Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name:  Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.7
        
    - name:  Clear Gradle Cache
      run: |
        rm -rf ~/.gradle/caches/
        rm -rf ~/.gradle/wrapper/
        
    - name:  Verify Project Structure
      run: |
        echo " Project structure verification:"
        ls -la android_keyboard/
        echo " Gradle wrapper check:"
        ls -la android_keyboard/gradlew*
        echo " Gradle wrapper properties:"
        cat android_keyboard/gradle/wrapper/gradle-wrapper.properties
        echo " Assets check:"
        ls -la android_keyboard/app/src/main/assets/
        
    - name:  Make Gradlew Executable
      run: chmod +x android_keyboard/gradlew
      
    - name:  Clean Project
      working-directory: android_keyboard
      run: ./gradlew clean
        
    - name:  Build Debug APK
      working-directory: android_keyboard
      run: ./gradlew assembleDebug
        
    - name:  Build Release APK
      working-directory: android_keyboard
      run: ./gradlew assembleRelease
        
    - name:  Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name:  Potomitan-Kreyol-Keyboard-DEBUG
        path: android_keyboard/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name:  Upload Release APK  
      uses: actions/upload-artifact@v4
      with:
        name:  Potomitan-Kreyol-Keyboard-RELEASE
        path: android_keyboard/app/build/outputs/apk/release/*.apk
        retention-days: 90
