name: 🇬🇵 Build Potomitan Kreyol Keyboard APK

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - '.github/workflows/**'
      - 'Dictionnaries/**'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - 'Dictionnaries/**'
  workflow_dispatch:

jobs:
  build:
    name: 📱 Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7
        
    - name: 🔐 Setup Keystore
      run: |
        cd android_keyboard
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/potomitan-keystore.jks
        echo "Keystore créé avec succès"
        ls -la app/potomitan-keystore.jks
        
    - name: 🧹 Clean project
      run: cd android_keyboard && gradle clean --no-daemon
        
    - name: 📱 Build Debug APK
      run: cd android_keyboard && gradle assembleDebug --no-daemon
        
    - name: 📱 Build Release APK
      run: cd android_keyboard && gradle assembleRelease --no-daemon
      env:
        KEYSTORE_FILE: app/potomitan-keystore.jks
        # Test avec valeurs par défaut - pas de variables de mot de passe
        
    - name: 🧹 Cleanup Keystore
      run: |
        cd android_keyboard
        rm -f app/potomitan-keystore.jks
        echo "Keystore nettoyé pour sécurité"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-DEBUG
        path: android_keyboard/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-RELEASE
        path: android_keyboard/app/build/outputs/apk/release/*.apk
        retention-days: 90

  release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Download Release APK
      uses: actions/download-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-RELEASE
        path: ./release-apk
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-apk/*.apk
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}