name: 🇸🇷 Build Potomitan Kreyol Keyboard APK & AAB

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - '.github/workflows/**'
      - 'Dictionnaries/**'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - 'Dictionnaries/**'
  workflow_dispatch:

jobs:
  build:
    name: 📱 Build APK & AAB
    runs-on: ubuntu-latest
    
    # 🔐 Variables d'environnement globales pour tout le job
    env:
      KEYSTORE_FILE: potomitan-keystore.jks
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Generate Fresh Kreyòl Dictionary
      run: |
        echo "🔄 Generating fresh Kreyòl dictionary from Hugging Face..."
        echo "🔑 Token configuré: $(if [ -n "$HF_TOKEN" ]; then echo "✅ Oui"; else echo "❌ Non"; fi)"
        
        # Install jq for JSON processing
        sudo apt-get update && sudo apt-get install -y jq
        
        cd Dictionnaires
        python -m pip install --upgrade pip
        pip install datasets huggingface_hub
        python KreyolComplet.py
        
        # Vérifier que les fichiers ont été générés dans clavier_creole/assets/
        if [ -f "../clavier_creole/assets/creole_dict.json" ] && [ -f "../clavier_creole/assets/creole_ngrams.json" ]; then
          echo "✅ Dictionary files generated successfully"
          
          # Copier depuis Flutter assets vers Android assets
          cp ../clavier_creole/assets/creole_dict.json ../android_keyboard/app/src/main/assets/
          cp ../clavier_creole/assets/creole_ngrams.json ../android_keyboard/app/src/main/assets/
          
          # Informations sur le dictionnaire
          DICT_SIZE=$(jq length ../clavier_creole/assets/creole_dict.json)
          NGRAM_SIZE=$(jq '.predictions | length' ../clavier_creole/assets/creole_ngrams.json)
          echo "📊 Dictionary: $DICT_SIZE words, $NGRAM_SIZE N-grams"
          
          echo "DICT_SIZE=$DICT_SIZE" >> $GITHUB_ENV
          echo "NGRAM_SIZE=$NGRAM_SIZE" >> $GITHUB_ENV
        else
          echo "❌ Dictionary generation failed - files not found in clavier_creole/assets/"
          echo "🔍 Checking what was generated..."
          ls -la ../clavier_creole/assets/ || echo "Directory not found"
          ls -la ./ || echo "Current directory listing failed"
          exit 1
        fi
        
    - name: 🔐 Setup Keystore
      run: |
        cd android_keyboard
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/potomitan-keystore.jks
        echo "Keystore créé avec succès"
        ls -la app/potomitan-keystore.jks
        
    - name: 🧹 Clean project
      run: cd android_keyboard && gradle clean --no-daemon
        
    - name: 📱 Build Debug APK
      run: cd android_keyboard && gradle assembleDebug --no-daemon
        
    - name: 📱 Build Release APK
      run: cd android_keyboard && gradle assembleRelease --no-daemon
        
    - name: 📦 Build Debug AAB (Android App Bundle)
      run: cd android_keyboard && gradle bundleDebug --no-daemon
        
    - name: 📦 Build Release AAB (Android App Bundle)
      run: cd android_keyboard && gradle bundleRelease --no-daemon
        
    - name: 🧹 Cleanup Keystore
      run: |
        cd android_keyboard
        rm -f app/potomitan-keystore.jks
        echo "Keystore nettoyé pour sécurité"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-DEBUG
        path: android_keyboard/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-RELEASE
        path: android_keyboard/app/build/outputs/apk/release/*.apk
        retention-days: 90
        
    - name: Upload Debug AAB
      uses: actions/upload-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-AAB-DEBUG
        path: android_keyboard/app/build/outputs/bundle/debug/*.aab
        retention-days: 30
        
    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-AAB-RELEASE
        path: android_keyboard/app/build/outputs/bundle/release/*.aab
        retention-days: 90

  release:
    name: 🚀 Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Download Release APK
      uses: actions/download-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-RELEASE
        path: ./release-apk
        
    - name: Download Release AAB
      uses: actions/download-artifact@v4
      with:
        name: Potomitan-Kreyol-Keyboard-AAB-RELEASE
        path: ./release-aab
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./release-apk/*.apk
          ./release-aab/*.aab
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}