name: Build Potomitan Kreyol Keyboard APK

on:
  push:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - '.github/workflows/**'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Samsung-Compatible APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        
    - name: Make Gradlew Executable
      run: chmod +x android_keyboard/gradlew
      
    - name: Clean Project
      run: |
        cd android_keyboard
        ./gradlew clean

    - name: Build Debug APK
      run: |
        cd android_keyboard
        ./gradlew assembleDebug
        
    - name: Build Release APK
      run: |
        cd android_keyboard
        ./gradlew assembleRelease
