name: 🏗️ Build Potomitan Kreyol Keyboard APK

on:
  push:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'android_keyboard/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: 📱 Build Samsung-Compatible APK
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🐘 Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        
    - name: 📄 Make Gradlew Executable
      run: chmod +x android_keyboard/gradlew
      
    - name: 🧹 Clean Project
      run: |
        cd android_keyboard
        ./gradlew clean
                
    - name: 🔨 Build Debug APK (Samsung Compatible)
      run: |
        cd android_keyboard
        ./gradlew assembleDebug
        
    - name: 🔨 Build Release APK (Samsung Compatible)
      run: |
        cd android_keyboard
        ./gradlew assembleRelease
        
    - name: 📁 List Built APKs
      run: |
        echo "🎯 APK Files Built:"
        find android_keyboard/app/build/outputs/apk -name "*.apk" -exec ls -la {} \;
        
    - name: 📤 Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: 📱 Potomitan-Kreyol-Keyboard-DEBUG-Samsung
        path: android_keyboard/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: 📤 Upload Release APK  
      uses: actions/upload-artifact@v4
      with:
        name: 📱 Potomitan-Kreyol-Keyboard-RELEASE-Samsung
        path: android_keyboard/app/build/outputs/apk/release/*.apk
        retention-days: 90
        
    - name: 📊 APK Info
      run: |
        echo "🎉 Build completed successfully!"
        echo ""
        echo "📱 Debug APK (Easy Installation):"
        ls -la android_keyboard/app/build/outputs/apk/debug/*.apk
        echo ""
        echo "📱 Release APK (Production):"
        ls -la android_keyboard/app/build/outputs/apk/release/*.apk
        echo ""
        echo "🔗 Download APKs from GitHub Actions Artifacts section"
        echo "💡 For Samsung tablets: Try DEBUG version first (easier to install)"
        
  # Job pour créer une release automatique sur les tags
  release:
    name: 🚀 Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      
    - name: 📥 Download Debug APK
      uses: actions/download-artifact@v4
      with:
        name: 📱 Potomitan-Kreyol-Keyboard-DEBUG-Samsung
        path: ./apk-debug/
        
    - name: 📥 Download Release APK
      uses: actions/download-artifact@v4
      with:
        name: 📱 Potomitan-Kreyol-Keyboard-RELEASE-Samsung
        path: ./apk-release/
        
    - name: 🚀 Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./apk-debug/*.apk
          ./apk-release/*.apk
        name: Potomitan Kreyol Keyboard ${{ github.ref_name }}
        body: |
          ## 📱 Potomitan Kreyol Keyboard ${{ github.ref_name }}
          
          ### 🔥 Highlights
          - ✅ Samsung Ultra-Compatible APKs
          - ✅ Enhanced multi-source suggestions ("sou" → "soudé")
          - ✅ Real-time contextual predictions
          - ✅ Full Creole dictionary + N-grams support
          
          ### 📋 Installation Instructions
          
          **🎯 For Samsung Tablets (Recommended)**:
          1. Download **DEBUG APK** (easier to install)
          2. Enable "Unknown Sources" in Settings → Security
          3. Install APK through "My Files" app
          
          **📱 APK Variants**:
          - **DEBUG**: `Potomitan_Kreyol_Keyboard_v1.2-Samsung_debug_*.apk` (Recommended for Samsung)
          - **RELEASE**: `Potomitan_Kreyol_Keyboard_v1.2-Samsung_release_*.apk` (Production)
          
          ### 🛠️ Technical Details
          - **ApplicationId**: `com.potomitan.kreyolkeyboard`
          - **Target SDK**: 33 (Samsung optimized)  
          - **Architectures**: arm64-v8a, armeabi-v7a
          - **Samsung Compatibility**: Ultra-optimized
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
