name: 🏷️ Create Tag v2.5.0

on:
  workflow_dispatch:
    inputs:
      create_tag:
        description: "Create v2.5.0 tag and trigger release"
        required: true
        default: true
        type: boolean

jobs:
  create-tag-v2-5-0:
    name: 🏷️ Create v2.5.0 Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: 🔍 Verify Version in build.gradle
      working-directory: android_keyboard
      run: |
        VERSION_FROM_GRADLE=$(grep "versionName" app/build.gradle | sed 's/.*"\(.*\)".*/\1/')
        echo "Version in build.gradle: $VERSION_FROM_GRADLE"
        if [[ "$VERSION_FROM_GRADLE" != "2.5.0" ]]; then
          echo "❌ Version mismatch! Expected 2.5.0, got $VERSION_FROM_GRADLE"
          echo "Please update versionName in app/build.gradle to '2.5.0'"
          exit 1
        fi
        echo "✅ Version check passed: $VERSION_FROM_GRADLE"
        
    - name: 🏷️ Create and Push Tag v2.5.0
      run: |
        # Configuration Git
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Vérifier si le tag existe déjà
        if git rev-parse "v2.5.0" >/dev/null 2>&1; then
          echo "⚠️ Tag v2.5.0 already exists"
          echo "Deleting existing tag..."
          git tag -d v2.5.0
          git push origin :refs/tags/v2.5.0 || true
        fi
        
        # Créer le nouveau tag
        echo "🏷️ Creating tag v2.5.0..."
        git tag -a v2.5.0 -m "🇬🇵 Klavié Kreyòl Karukera v2.5.0 • Potomitan™

        Nouvelle version stable du clavier créole guadeloupéen !
        
        🎯 Nouveautés v2.5.0:
        - 🔧 Amélioration majeure du système Shift
        - 🐛 Correction barre espace 
        - 📊 Logs de débogage étendus
        - 🔄 Optimisation mode clavier
        - 🎨 Stabilité interface
        
        ✨ Fonctionnalités:
        - 🌈 Design moderne caribéen
        - 📝 Suggestions intelligentes (5910 mots créoles)
        - 🔤 Accents créoles natifs (à, è, ò, etc.)
        - 📚 Sources littéraires intégrées
        - 🎯 Optimisation Samsung
        
        Alé douvan épi klavié kreyòl-la ! ⌨️✨"
        
        # Pousser le tag
        echo "📤 Pushing tag to GitHub..."
        git push origin v2.5.0
        
        echo "✅ Tag v2.5.0 created and pushed successfully!"
        echo "🚀 This will trigger the release workflow automatically."
        
    - name: 🎉 Success Message
      run: |
        echo "🎉 Tag v2.5.0 created successfully!"
        echo ""
        echo "📋 Next steps:"
        echo "1. ✅ Tag v2.5.0 has been pushed to GitHub"
        echo "2. 🚀 Release workflow will start automatically"
        echo "3. 📱 APKs will be built and attached to the release"
        echo "4. 🔗 Release will be available at: https://github.com/${{ github.repository }}/releases/tag/v2.5.0"
        echo ""
        echo "⏱️ Expected completion time: ~5-10 minutes"