name:  Build and Release Potomitan Kreyol Keyboard

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., v1.1.0)"
        required: true
        default: "v1.1.0"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: ☕ Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        
    - name: 🔧 Make gradlew executable
      run: chmod +x android_keyboard/gradlew
      
    - name: 💾 Check system resources
      run: |
        echo "=== DISK SPACE ==="
        df -h
        echo "=== MEMORY ==="
        free -h
        echo "=== CPU INFO ==="
        nproc
        echo "=== ENVIRONMENT VARIABLES ==="
        env | grep -E "(GRADLE|JAVA|ANDROID)" || echo "No Gradle/Java/Android env vars"
        
    - name: 🔍 Verify gradlew and environment
      run: |
        echo "Working directory: $(pwd)"
        echo "List files in android_keyboard:"
        ls -la android_keyboard/
        echo "Check gradlew:"
        ls -la android_keyboard/gradlew
        echo "Java version:"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: 🏗️ Force Gradle wrapper setup
      working-directory: android_keyboard
      run: |
        chmod +x gradlew
        ./gradlew wrapper --gradle-version=8.4
        
    - name: Clean project
      working-directory: android_keyboard
      run: |
        gradle clean
        
    - name: Build Debug APK
      working-directory: android_keyboard
      run: |
        gradle assembleDebug
      
    - name: Build Release APK
      working-directory: android_keyboard
      run: |
        gradle assembleRelease
        
    - name: 📦 Find APK files
      id: apk_files
      working-directory: android_keyboard
      run: |
        DEBUG_APK=$(find app/build/outputs/apk/debug -name "*.apk" | head -1)
        RELEASE_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -1)
        
        echo "Found Debug APK: $DEBUG_APK"
        echo "Found Release APK: $RELEASE_APK"
        
        echo "debug_apk=$DEBUG_APK" >> $GITHUB_OUTPUT
        echo "release_apk=$RELEASE_APK" >> $GITHUB_OUTPUT
        
    - name: 📊 APK Info
      working-directory: android_keyboard
      run: |
        echo "🔍 Debug APK:"
        ls -lh "${{ steps.apk_files.outputs.debug_apk }}"
        echo "🔍 Release APK:"
        ls -lh "${{ steps.apk_files.outputs.release_apk }}"
        
    - name: 🚀 Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: 🇬🇵 Klavié Kreyòl Karukera ${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## 🇬🇵 Klavié Kreyòl Karukera • Potomitan™
          
          **Nouveau clavier créole pour la Guadeloupe !**
          
          ### ✨ Fonctionnalités :
          - 🌈 Design moderne caribéen (bleu caraïbe, jaune soleil, vert canne)
          - 📝 Suggestions intelligentes basées sur un vrai dictionnaire créole
          - 🔤 Accents créoles (à, è, ò, etc.) avec long-press
          - 📚 Dictionnaire de 5910 mots créoles authentiques
          - 🎯 Sources littéraires intégrées (Telchid, Rupaire, Fontes, etc.)
          
          ### 📱 Installation :
          1. Téléchargez le fichier **Release APK** (recommandé) ou Debug APK
          2. Autorisez l'installation d'applications inconnues
          3. Installez l'APK
          4. Activez le clavier dans Paramètres → Langues et saisie
          
          ### 📊 Tailles des fichiers :
          - **Release APK** : ~2.6 MB (optimisé)
          - **Debug APK** : ~3.4 MB (avec infos de debug)
          
          ---
          **Alé douvan épi klavié kreyòl-la !** ⌨️✨
        files: |
          android_keyboard/${{ steps.apk_files.outputs.debug_apk }}
          android_keyboard/${{ steps.apk_files.outputs.release_apk }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
