name:  Build and Release Potomitan Kreyol Keyboard

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., v1.1.0)"
        required: true
        default: "v1.1.0"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7
        
    - name: 🔐 Setup Keystore
      run: |
        cd android_keyboard
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/potomitan-keystore.jks
        echo "Keystore créé avec succès"
        ls -la app/potomitan-keystore.jks
        
    - name: Clean project
      run: |
        cd android_keyboard && gradle clean --no-daemon
        
    - name: Build Debug APK
      run: |
        cd android_keyboard && gradle assembleDebug --no-daemon
      
    - name: Build Release APK
      run: |
        cd android_keyboard && gradle assembleRelease --no-daemon
      env:
        KEYSTORE_FILE: app/potomitan-keystore.jks
        STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        
    - name: 📦 Find APK files
      id: apk_files
      run: |
        cd android_keyboard
        DEBUG_APK=$(find app/build/outputs/apk/debug -name "*.apk" | head -1)
        RELEASE_APK=$(find app/build/outputs/apk/release -name "*.apk" | head -1)
        
        echo "Found Debug APK: $DEBUG_APK"
        echo "Found Release APK: $RELEASE_APK"
        
        echo "debug_apk=$DEBUG_APK" >> $GITHUB_OUTPUT
        echo "release_apk=$RELEASE_APK" >> $GITHUB_OUTPUT
        
    - name: 🧹 Cleanup Keystore
      run: |
        cd android_keyboard
        rm -f app/potomitan-keystore.jks
        echo "Keystore nettoyé pour sécurité"
        
    - name: 📊 APK Info
      run: |
        cd android_keyboard
        echo "🔍 Debug APK:"
        ls -lh "${{ steps.apk_files.outputs.debug_apk }}"
        echo "🔍 Release APK:"
        ls -lh "${{ steps.apk_files.outputs.release_apk }}"
        
    - name: 🚀 Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: 🇬🇵 Klavié Kreyòl Karukera ${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## 🇬🇵 Klavié Kreyòl Karukera • Potomitan™
          
          **Nouveau clavier créole pour la Guadeloupe !**
          
          ### ✨ Fonctionnalités :
          - 🌈 Design moderne caribéen (bleu caraïbe, jaune soleil, vert canne)
          - 📝 Suggestions intelligentes basées sur un vrai dictionnaire créole
          - 🔤 Accents créoles (à, è, ò, etc.) avec long-press
          - 📚 Dictionnaire de 5910 mots créoles authentiques
          - 🎯 Sources littéraires intégrées (Telchid, Rupaire, Fontes, etc.)
          
          ### 📱 Installation :
          1. Téléchargez le fichier **Release APK** (recommandé) ou Debug APK
          2. Autorisez l'installation d'applications inconnues dans les paramètres Android
          3. Installez l'APK en touchant le fichier téléchargé
          4. Activez le clavier dans **Paramètres → Système → Langues et saisie → Claviers virtuels**
          5. Sélectionnez **Potomitan Kreyol Keyboard**
          
          ### 📊 Tailles des fichiers :
          - **Release APK** : ~2.6 MB (optimisé pour la production)
          - **Debug APK** : ~3.4 MB (avec outils de débogage)
          
          ### 🔒 Sécurité :
          - Code source ouvert et auditable
          - Pas de trackers ou analytics
          - Permissions minimales requises
          
          ---
          **Alé douvan épi klavié kreyòl-la !** ⌨️✨
        files: |
          android_keyboard/${{ steps.apk_files.outputs.debug_apk }}
          android_keyboard/${{ steps.apk_files.outputs.release_apk }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
