name: 🚀 Simple Release v2.5.0

on:
  push:
    tags:
      - "v2.5.0"
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x android_keyboard/gradlew
      
    - name: Clean project
      run: |
        cd android_keyboard
        ./gradlew clean
        
    - name: Build debug APK
      run: |
        cd android_keyboard
        ./gradlew assembleDebug
        
    - name: Build release APK  
      run: |
        cd android_keyboard
        ./gradlew assembleRelease
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v2.5.0"
        name: "Potomitan Kreyol Keyboard v2.5.0"
        files: |
          android_keyboard/app/build/outputs/apk/debug/*.apk
          android_keyboard/app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}